version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Vite dev server
      - "6006:6006"  # Storybook
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  production:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"  # Main app
      - "6006:6006"  # Storybook
    restart: always